apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project
  labels:
    app: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - image: arnoldrx/capstone-project:latest
          name: capstone-project
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: nodejs-server
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project
  labels:
    name: capstone-project
spec:
  selector:
    app: capstone-project
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 80
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capstone-project
  namespace: kube-system
  labels:
    app: capstone-project
  annotations:
    alb.ingress.kubernetes.io/target-type: instance


spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone-project
                port:
                  number: 8000
